services:
  dev_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: cv-baseimage-01
    container_name: ${PROJECT_NAME}-dev
    environment:
      - DISPLAY=$CONTAINER_DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/rosuser/.Xauthority
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/rosuser/repo
      - ${DATASET}:/home/rosuser/repo/dataset:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/home/rosuser/.Xauthority:rw
    command: /bin/bash
    stdin_open: true
    tty: true
